# static/admin/config.yml

backend:
  name: github
  repo: JonMGuy01/hugo-reborn # Your actual repo name and username
  branch: master # Or 'main' if that's your default branch
  # REMOVE these two lines:
  # base_url: https://theguys.online/
  # auth_endpoint: api/auth
  # ADD these two lines:
  auth_type: implicit
  app_id: Ov23li2bxkZR8lC34iCs # <--- PASTE YOUR GITHUB OAUTH APP CLIENT ID HERE
  auth_scope: repo # Optional, but good practice if you specified it in your GitHub app setup

media_folder: "static/uploads"
public_folder: "/uploads"
