# static/admin/config.yml

backend:
  name: github
  repo: JonMGuy01/hugo-reborn
  branch: master
  base_url:https://theguys.online
  auth_endpoint: /api/auth


media_folder: "static/uploads" # Choose one: "static/img" or "static/uploads"
public_folder: "/uploads"      # Choose one: "/img" or "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false # Added this based on your conflict output
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" } # Added this
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }

  - name: "pages"
    label: "Site Pages"
    files:
      - file: "content/_index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/about.md"
        label: "About Us"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }