backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads" # Folder where uploaded media will be stored relative to site root
public_folder: "/uploads"     # Public path for accessing uploaded media

ccollections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/_index.md" # <-- This is the crucial part for Hugo!
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Hero Image", name: "hero_image", widget: "image", required: false } # Example custom field
          - { label: "Body", name: "body", widget: "markdown" }
          # Add any other front matter fields you use on your homepage
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
